# Generated by Django 5.2.3 on 2025-06-19 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0003_roomcompletion_certificate'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='roomcompletion',
            index=models.Index(fields=['user', 'is_completed'], name='lms_roomcom_user_id_739b3b_idx'),
        ),
        migrations.AddIndex(
            model_name='roomcompletion',
            index=models.Index(fields=['room', 'is_completed'], name='lms_roomcom_room_id_71b7ab_idx'),
        ),
        migrations.AddIndex(
            model_name='roomcompletion',
            index=models.Index(fields=['completed_at'], name='lms_roomcom_complet_104357_idx'),
        ),
        migrations.AddIndex(
            model_name='roomcompletion',
            index=models.Index(fields=['final_exam_score'], name='lms_roomcom_final_e_f0bf44_idx'),
        ),
        migrations.AddIndex(
            model_name='sectioncompletion',
            index=models.Index(fields=['user', 'is_completed'], name='lms_section_user_id_e45f53_idx'),
        ),
        migrations.AddIndex(
            model_name='sectioncompletion',
            index=models.Index(fields=['section', 'is_completed'], name='lms_section_section_fa23f8_idx'),
        ),
        migrations.AddIndex(
            model_name='sectioncompletion',
            index=models.Index(fields=['completed_at'], name='lms_section_complet_4a7cd0_idx'),
        ),
        migrations.AddIndex(
            model_name='useranswer',
            index=models.Index(fields=['user', 'is_correct'], name='lms_userans_user_id_9bcf18_idx'),
        ),
        migrations.AddIndex(
            model_name='useranswer',
            index=models.Index(fields=['question', 'is_correct'], name='lms_userans_questio_37a35e_idx'),
        ),
        migrations.AddIndex(
            model_name='useranswer',
            index=models.Index(fields=['answered_at'], name='lms_userans_answere_390275_idx'),
        ),
    ]
