# Generated by Django 5.2.3 on 2025-06-19 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0004_roomcompletion_lms_roomcom_user_id_739b3b_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='roomcompletion',
            name='lms_roomcom_user_id_739b3b_idx',
        ),
        migrations.RemoveIndex(
            model_name='roomcompletion',
            name='lms_roomcom_room_id_71b7ab_idx',
        ),
        migrations.RemoveIndex(
            model_name='roomcompletion',
            name='lms_roomcom_complet_104357_idx',
        ),
        migrations.RemoveIndex(
            model_name='roomcompletion',
            name='lms_roomcom_final_e_f0bf44_idx',
        ),
        migrations.RemoveIndex(
            model_name='sectioncompletion',
            name='lms_section_user_id_e45f53_idx',
        ),
        migrations.RemoveIndex(
            model_name='sectioncompletion',
            name='lms_section_section_fa23f8_idx',
        ),
        migrations.RemoveIndex(
            model_name='sectioncompletion',
            name='lms_section_complet_4a7cd0_idx',
        ),
        migrations.RemoveIndex(
            model_name='useranswer',
            name='lms_userans_user_id_9bcf18_idx',
        ),
        migrations.RemoveIndex(
            model_name='useranswer',
            name='lms_userans_questio_37a35e_idx',
        ),
        migrations.RemoveIndex(
            model_name='useranswer',
            name='lms_userans_answere_390275_idx',
        ),
    ]
